INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('000','OBRAS GENERALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('001','CONOCIMIENTO CIENCIA ERUDICIÓN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('002','EL LIBRO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('010','CIENCIA Y TÉCNICA BIBLIOGRÁFICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('011','Bibliografías generales y universales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('012','Bibliografías individuales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('013','Bibliografías de determinados grupos de autores');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('014','Bibliografías de obras anónimas y publicadas bajo seudónimo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('015','Bibliografías nacionales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('016','Bibliografías por materias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('017','Catálogos sistemáticos impresos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('018','Catálogos impresos de autores');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('019','Catálogos diccionarios impresos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('020','BIBLIOTECOLOGIA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('021','Creación, finalidad y desarrollo de las bibliotecas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('022','Edificios de bibliotecas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('023','Dirección y personal de la biblioteca');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('024','Reglamentos para uso de la biblioteca');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('025','Administración');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('026','Bibliotecas especializadas - Colecciones especiales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('027','Bibliotecas generales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('028','La lectura y su orientación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('029','Métodos y materia para el trabajo intelectual');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('030','ENCICLOPEDIAS GENERALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('031','Enciclopedias norteamericanas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('032','Enciclopedias británicas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('033','Enciclopedias alemanas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('034','Enciclopedias francesas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('035','Enciclopedias italianas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('036','Enciclopedias españolas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('037','Enciclopedias rusas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('038','Enciclopedias escandinavas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('039','Otras enciclopedias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('040','COLECCIONES DE ENSAYOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('050','PUBLICACIONES PERIODOCAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('060','SOCIEDADES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('069','MUSEOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('070','PERIODISMO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('071','Periódicos norteamericanos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('072','Periódicos ingleses');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('073','Periódicos alemanes');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('074','Periódicos franceses');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('075','Periódicos italianos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('076','Periódicos españoles');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('077','Periódicos rusos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('078','Periódicos escandinavos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('079','Historia individual de periódicos de otros países');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('080','POLIGRAFÍAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('081','Colecciones de obras de un solo autor');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('082','Colecciones de obras de varios autores');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('090','LIBROS RAROS Y CURIOSOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('091','Manuscritos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('092','Libros xilográficos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('093','Incunables');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('094','Impresiones raras y valiosas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('095','Encuadernaciones raras y valiosas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('096','Ilustraciones o materiales raros y valiosos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('097','Marcas del impresor Ex libris');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('098','Obras raras por sus caracteres extrínsecos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('100','FILOSOFÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('101','Estética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('109','Historia de la filosofía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('110','METAFÍSICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('111','Ontología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('112','Metodología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('113','Cosmología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('114','   Espacio');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('115','   Tiempo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('116','   Movimiento');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('117','   Materia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('118','   Energía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('119','   Cantidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('120','TEORÍAS METAFÍSICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('121','Gnoseología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('123','Libertad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('124','Teleología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('125','Infinito');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('128','El alma');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('130','RAMAS DE LA PSICOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('131','Psicología Fisiológica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('132','Psicología de anormales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('133','Ocultismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('134','Hipnotismo Mesmerismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('135','Sueños');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('136','Psicología  genética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('137','Psicología individual');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('138','Fisiognómica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('139','Frenología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('140','SISTEMAS FILOSÓFICOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('141','Idealismo Trascendentalismo Espiritualismo Subjetivismo Individualismo Romanticismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('142','Filosofía crítica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('143','Intuicionismo Bengsonismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('144','Empirismo Pragmatismo Humanismo Instrumentalismo Utilitarismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('145','Sensualismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('146','Naturalismo Materialismo Positivismo Atomismo Mecanicismo Neomecanicismo Dinamismo Energetismo Evolucionismo Transformismo Comtismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('147','Pamteísmo Panenteísmo Monismo Animismo Vitalismo Dualismo Pluralismo Paralelismo Ocasionalismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('148','Eclecticismo Liberalismo Sincretismo Dogmatismo Tradicionalismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('149','Otros sistemas filosóficos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('150','PSICOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('151','Inteligencia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('153','Cognición');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('154','Memoria Aprendizaje');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('155','Imaginación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('156','Intuición');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('157','Emoción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('158','Conación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('159','Motivación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('160','LÓGICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('161','Inducción y método científico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('162','Deducción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('163','Fe');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('164','Sistemas de lógica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('170','ÉTICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('171','Ética teórica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('172','Ética política');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('173','Moral de la familia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('174','Ética  profesional o moral en los negocios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('175','Moral en las diversiones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('176','Moral sexual');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('177','Ética  social');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('178','Ética  de la templanza');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('179','Otros sistemas de ética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('180','FILOSOFÍA ANTIGUA Y ORIENTAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('181','Filosofía oriental');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('182','Filosofía  presocrática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('183','Los sofistas y la filosofía socrática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('184','Filosofía platónica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('185','Filosofía aristotélica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('186','Escepticismo y neoplatonismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('187','Epicureísmo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('188','Estoicismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('189','Filosofía medioeval');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('190','FILOSOFÍA MODERNA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('191','Filosofía estadounidense');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('192','Filosofía  inglesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('193','Filosofía alemana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('194','Filosofía francesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('195','Filosofía italiana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('196','Filosofía española y portuguesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('197','Filosofía rusa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('198','Filosofía  escandinava');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('199','Otras filosofías modernas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('200','RELIGIÓN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('210','RELIGIÓN NATURAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('211','Deísmo Ateísmo Teísmo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('212','Panteísmo Teosofía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('213','Creación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('214','Providencia fatalismo Teodicea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('215','Religión y ciencia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('216','El bien y el mal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('217','Oración y culto');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('218','Inmortalidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('219','Analogías Doctrina de las correspondencias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('220','BIBLIA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('221','Antiguo Testamento');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('222','   Libros históricos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('223','   Libros sapienciales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('224','   Libros proféticos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('225','Nuevo Testamento');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('226','   Evangelios Hechos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('227','   Epístolas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('228','   Apocalipsis de San Juan');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('229','Libros apócrifos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('230','TEOLOGÍA SISTEMÁTICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('231','Dios La Trinidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('232','Cristología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('233','El Hombre');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('234','Soteriología Salvación Sacramentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('235','Santos Ángeles Demonios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('236','Escatología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('237','Vida Futura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('238','Fundamentos de la creencia religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('239','Apologética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('240','TEOLOGÍA PRÁCTICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('241','Teología moral');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('242','Meditación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('244','Cuentos Alegorías Sátiras');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('245','Himnología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('246','Simbolismos cristiano');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('247','Estética de la iglesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('248','Devición privada Ascética Mística');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('249','Devociones y oraciones en familia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('250','TEOLOGÍA PASTORAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('251','Homilética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('252','Sermones e instrucciones pastorales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('253','Ministros eclesiásticos Párrocos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('254','Administración eclesiástica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('258','Obra social de la iglesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('259','Organización y dirección de grupos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('260','IGLESIA CRISTIANA EN GENERAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('261','Teología social cristiana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('262','Gobierno de la iglesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('263','Día del Señor');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('264','Culto público');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('265','Sacramentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('266','Misiones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('267','Asociaciones religiosas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('268','Educación religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('269','Obra de conversión evangélica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('270','HISTORIA DE LA IGLESIA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('271','Ordenes religiosas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('272','Persecuciones religiosas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('273','Herejías');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('274-279','Historia de la iglesia en los diferentes países');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('280','IGLESIAS Y SECTAS CRISTIANAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('281','Iglesias primitivas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('282','Iglesia Católica Apostólica Romana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('283','Iglesia Anglicana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('284','Protestantismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('285','Presbiterianismo, congregacionalismo y otros grupos reformados');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('286','Iglesias baptistas y otras sectas que practican el bautismo por inmerisón');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('287','Metodismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('288','Unitarismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('289','Otras sectas cristianas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('290','RELIGIONES NO CRISTIANAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('291','Mitología comparada');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('292','Religión y mitología griega y romana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('293','Religión y mitología teutónica y nórdica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('294','Budismo y Brahmanismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('295','Religiones asiáticas no semíticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('296','Judaísmo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('297','Islamismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('299','Religiones semíticas y otrs religiones no cristianas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('300','CIENCIAS SOCIALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('301','SOCIOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('309','HISTORIA DE LAS CIENCIAS SOCIALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('310','ESTADÍSTICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('311','Métodos estadísticos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('312','Demografía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('320','CIENCIAS POLÍTICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('321','Tipos de Estado');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('322','Jurisdicción del Estado');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('323','Relaciones del Estadp con individuos o grupos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('324','Sufragio Elecciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('325','Migración internacional y colonización');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('326','Esclavitud');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('327','Relaciones internacionales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('328','Legislación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('329','Partidos políticos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('330','ECONOMÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('331','Trabajo y problemas del trabajo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('332','Finanzas privadas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('333','Economía de tierras');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('334','Cooperación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('335','Sistemas colectivistas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('336','Hacienda Pública');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('337','Política arancelaria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('338','Producción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('339','Ingreso y riqueza');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D340','DERECHO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D341','Derecho internacional');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D342','Derecho constitucional');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D343','Derecho penal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D344','Derecho administrativo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D345','Derecho procesal penal y civil');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D346','Derecho civil');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D347','Derecho comercial');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D348','Derechos especiales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('D349','Historia del derecho. Derecho clasificado por los países');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('350','ADMINISTRACIÓN PÚBLICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('351','Problemas de la administración pública');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('352','Gobierno local');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('353','Gobierno federal y estatal de los EE.UU. de Norteamérica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('354','Administración de las ramas del poder ejecutivo de otros países');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('355','Ciencia y arte militar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('356','Servivios y fuerzas terrestres');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('357','Caballería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('358','Fuerzas y servicios aéreos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('359','Fuerzas navales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('360','BIENESTAR SOCIAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('361','Servicio social e instituciones sociales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('362','Servicios de bienestar social');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('364','Criminología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('365','Penalogía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('366','Asociaciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('367','Clubes sociales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('368','Seguros');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('369','Otras asociaciones e instituciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('370','EDUCACIÓN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('371','Enseñanza');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('372','Enseñanza primaria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('373','Enseñanza secundaria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('374','Educación de adultos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('375','Programas de estudios (Curriculum) Programa de materias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('376','Educación femenina');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('377','Enseñanza moral y religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('378','Enseñanza universitaria y superior');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('379','La enseñanza y el estado');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('380','COMERCIO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('381','Comercio interior');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('382','Comercio internacional');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('383','Comunicación postal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('384','Comunicaciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('385','Transporte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('386','Transporte por ríos, canales y lagos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('387','Transporte marítimo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('387.7','Transporte aéreo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('388','Transporte por carreteras');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('389','Pesas y medidad Metrología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('390','COSTUMBRES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('392','Costumbres del ciclo de vida individual');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('393','Costumbres funerarias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('394','Costumbres políticas y sociales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('395','Etiqueta');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('396','Posición de la mujer en la sociedad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('397','Gitanos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('398','Folklore');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('399','Costumbres de guerra');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('400','LINGÜISTICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('408','COLECCIONES LENGUAS ARTIFICIALES UNIVERSALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('410','LINGÜISTICA COMPARADA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('411','Escritura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('412','Etimilogía Semántica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('413','Lexicografía Diccionarios políglotas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('414','Fonética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('415','Gramática Morfología Sintaxis');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('416','Prosodia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('417','Inscripciones Paleografía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('418','Textos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('419','Lenguaje mímico, simbólico o ideográfico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('420','INGLÉS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('430','ALEMÁN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('439','LENGUAS GERMÁNICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('440','FRANCES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('449','PROVENZAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('450','ITALIANO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('459','RUMANO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('460','CASTELLANO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('461','   Escritura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('462','   Derivaciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('463','   Diccionarios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('464','   Sinónimos Homónimos Antónimos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('465','   Gramática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('466','   Prosodia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('467','   Provincialismos Jerga Dialectología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('468','   Textos para la enseñanza del castellano');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('469','PORTUGUES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('470','LATÍN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('479','OTRAS LENGUAS ITÁLICAS LATÍN MEDIOEVAL Y MODERNO (LATÍN ECLESIÁSTICO)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('480','GRIEGO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('489','GRUPO HELÉNICO GRIEGO MODERNO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('490','OTRAS LENGUAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('491','Lenguas indoeuropeas e indo-hitita');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('492','Lenguas semíticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('493','Lenguas camíticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('494','Lenguas tungusas, mogolas, turco-tártaras, samoyedas, ugrofinesas y del grupo hiperbóreo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('495','Lenguas chino-tibetanas, japonesa-coreana, austroasiáticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('496','Lenguas africanas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('497','Lenguas de América del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('498','Lenguas de América del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('499','Lenguas austronesias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('500','CIENCIAS PURAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('508','COLECCIONES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('510','MATEMÁTICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('512','Álgebra');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('513','Geometría');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('514','Trigonometría');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('515','Geometría descriptiva');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('516','Geometría analítica euclideana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('517','Cálculo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('519','Probabilidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('520','ASTRONOMÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('521','Dinámica celeste');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('522','Observatorio e instrumentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('523','Astronomía descriptiva Astrofísica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('524','Mapas y tablas astronómicas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('525','Tierra');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('526','Geodesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('527','Astronomía aplicada a la navegación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('528','Almanaques naúticos y efemérides');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('529','Mediciones del tiempo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('530','FÍSICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('532','Mecánica de los líquidos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('533','Mecánica de los gases');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('534','Sonido');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('535','Óptica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('540','QUÍMICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('541','Fisicoquímica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('542','Aparatos y equipos para laboratorios químicos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('543','Análisis');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('544','Análisis cualitativo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('545','Análisis cuantitativo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('546','Química inorgánica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('547','Química Orgánica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('548','CRISTALOGRAFÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('549','MINERALOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('550','GEOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('551','Geología-física y dinámica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('552','Petrología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('553','Geología económica y aplicada');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('554','Geología de Europa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('555','Geología de Asia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('556','Geología de Africa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('557','Geología de América del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('558','Geología de América del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('559','Geología de Oceanía y de las regiones polares');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('560','PALEONTOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('561','Paleofitología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('562','Paleozoología de los invertebrados');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('563','Protozoa, porífera, cnidaria, achinodermata');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('564','Mollusca y Molluscoidea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('565','Arthropoda');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('566','Paleozoología de los vertebrados');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('567','Peces');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('568','Saurpsida (Reptiles y aves)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('569','Mammalia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('570','CIENCIAS BIOLÓGICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('571','Arquelogía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('572','Antropología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('573','Antropología física');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('574','Biología Ecología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('575','Evolución Genética');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('576','Microbiología');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('578','Técnicas biológicas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('579','Colecciones de historia natural y biológica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('580','BOTÁNICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('581','Fisiología y morfología vegetal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('582','Botánica sistemática o taxonómica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('583','Dicotiledóneas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('584','Monocotiledóneas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('585','Gimnospermas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('586','Criptógamas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('587','Pteridofitas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('588','Briofitas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('589','Talofitas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('590','ZOOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('591','Zoología general');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('592','Invertebrada');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('593','   Protozoa Mesozoa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('594','   Mollusca y molluscoidea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595','   Articulata');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.1','   Vermes');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.3','   Crustacea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.4','   Arachnida');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.5','   Onychophora');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.6','   Myriapoda');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('595.7','   Insecta (hexapoda)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('596','Chordates');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('597','   Peces');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('597.6','   Amphibia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('598','   Reptilia Aves');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('599','   Mammalia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('599.9','   Hombre');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('600','CIENCIA APLICADA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('608','PATENTE E INVENTOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('610','CIENCIAS MÉDICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('611','Anatomía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('612','Fisiología humana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('613','Higiene personal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('614','Salud pública y medicina preventiva');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('615','Terapéutica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('616','Patología interna y clínica médica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('617','Cirugía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('618','Ginecología y obstetricia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('618.9','Pediatría');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('618.97','GERONTOLOGÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('620','INGENIERÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('621','Ingeniería mecánica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('622','Ingeniería de minas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('623','Ingeniería militar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('624','Ingeniería estructural');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('625','Ingeniería del transporte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('627','Ingeniería hidráulica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('628','Ingeniería sanitaria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('629','Otras ramas de la ingeniería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('629.4','Viajes espaciales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('630','AGRICULTURA Y GANADERÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('631','Administración agrícola');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('632','Factores perjudiciales en la producción agrícola');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('633','Cultivos extensivos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('634','Fruticultura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('634.9','Dasonomía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('635','Horticultura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('636','Zootecnia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('637','Industria láctea y sus derivados');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('638','Cría de abejas, gusanos de seda y otros insectos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('639','Industria de la caza y de la pesca');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('640','ECONOMÍA DOMÉSTICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('641','Alimentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('642','Comidas y agasajos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('643','Plan de distribución de la casa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('645','Amueblado de la casa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('646','Indumentaria y aspecto personal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('647','Organización y administración de la casa y otros tipos de vivienda');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('648','Higiene y sanidad del hogar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('649','Cuidado de niños y enfermería en el hogar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('650','EMPRESAS Y SISYEMAS COMERCIALES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('651','Dirección de oficinas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('652','Escritura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('653','Taquigrafía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('655','Industria de las artes gráficas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('657','Contabilidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('658','Administración de empresas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('659','Otros temas relacionados con las empresas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('660','TECNOLOGÍA QUÍMICA QUÍMICA INDUSTRIAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('661','Productos químicos industriales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('662','Explosivos Tecnología de los combustibles Carbones de uso industrial');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('663','Bebidas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('664','Industria de los alimentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('665','Lubricantes Tecnología del petróleo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('666','Tecnología de la cerámica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('667','Limpieza y blanqueo Teñido');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('668','Otros materiales y productos de química orgánica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('669','Metalurgia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('670','MANUFACTURAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('671','Manufactura de metales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('672','Manufactura del hierro y del acero Aleaciones del hierro');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('673','Manufactura de otros metales y sus aleaciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('674','Industria de la madera');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('675','Industria de cueros y pieles');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('676','Manufactura de pulpa, papel y celulosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('677','Industria de textiles y de otros fibras');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('678','Caucho y manufacturas de caucho');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('679','Otras manufacturas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('680','MANUFACTURAS (Continuación)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('681','Manufacturas de instrumentos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('682','Herrería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('683','Armería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('684','Carpintería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('685','Manufactura de artículos de cuero');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('687','Industria de la ropa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('688','Fabricación de artículos pequeños');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('690','CONSTRUCCIÓN DE EDIFICIOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('691','Materiales de construcción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('692','Prácticas de construcción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('693','Sistemas de Construcción');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('694','Construcción en madera');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('695','Detalles de construcción de edificios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('696','Accesorios para construcción de edificios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('697','Técnicas de calefacción, ventilación y acondicionamiento de aire');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('698','Decoración de edificios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('700','ARTES Y RECREACIÓN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('701','FILOSOFÍA Y TEORÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('704','ENSAYOS, CONFERENCIAS, DISCURSOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('708','GALERÍAS, MUSEOS Y COLECCIONES PARTICULARES');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('709','HISTORIA DEL ARTE');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('710','ARQUITECTURA PAISAJISTA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('711','Planeamiento regional y urbano');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('712','Tipos de diseño de arquitectura paisajista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('713','Formación y conservación del paisaje');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('714','Temas acuáticos en arquitectura paisajista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('715','Árboles, arbustos y setos en arquitectura paisajista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('716','Plantas herbáceas o anuales en la arquitectura paisajista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('717','Construcción en arquitectura paisajista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('718','Planeamiento de cementerios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('719','Planeaminero de reservaciones de tierras y preservación del paisaje natural');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('720','ARQUITECTURA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('721','Construcción arquitectónica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('722','Arquitectura antigua');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('723','Arquitectura medioeval');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('724','Arquitectura moderna');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('725','Edificios públicos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('726','Arquitectura religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('727','Edificios de enseñanza');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('728','Arquitectura residencial');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('729','Diseños arquitectónicos y decoración');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('730','ESCULTURA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('731','Métodos y material');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('732','Escultura antigua Escultura primitiva');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('733','Escultura clásica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('734','Escultura medioeval');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('735','Escultura moderna');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('736','Talla de materiales especiales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('737','Numismática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('738','Escultura en cerámica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('739','Escultura en metal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('740','DIBUJO ARTE DECORATIVO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('741','Dibujo a pulso');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('742','Perspectiva');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('743','Anatomía en el dibujo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('744','Dibujo técnico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('745','Arte decorativo y diseño');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('746','Encajes Tapices tranajos de aguja');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('747','Decoración de interiores');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('748','Cristalería');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('749','Muebles y accesorios');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('750','PINTURA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('751','Métodos y material');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('752','Teoría y aplicación del color');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('753','Pintura épica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('754','Pintura costumbrista');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('755','Pintura religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('756','Pintura histórica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('757','Retratos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('758','Otros temas en pintura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('759','Historia de la pintura');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('760','GRABADO Y TÉCNICAS DE GRABADO');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('761','Grabado en relieve');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('762','Grabado en hueco (Intaglio) Granago en metal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('763','Grabado en superficie plana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('764','Cromolitografía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('765','Grabado en línea Grabado a puntos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('766','Aguatinta Mezzotinta');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('767','Aguafuerte Grabado a punta seca');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('768','Grabado mecánico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('769','Colecciones de grabados');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('770','FOTOGRAFÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('771','Material fotográfico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('772','Procedimientos fotográficos con sales metálicas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('773','Procedimientos fotográficos de pigmentación');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('778','Aplicaciones de la fotografía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('779','Colecciones de fotografías');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('780','MÚSICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('781','Teoría y técnica de la música');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('782','Música operística Música para la escena');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('783','Música religiosa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('784','Música vocal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('785','Conjuntos instrumentales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('786','Instrumentales de teclado');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('787','Instrumentos de cuerda');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('788','Instrumentos de viento');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('789','Instrumentos de percusión Instrumentos mecánicos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('790','RECREACIÓN');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('791','Diversiones y espectáculos públicos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('792','Teatro');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('793','Tertulias Otros entrenimientos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('794','Juegos de habilidad');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('795','Juegos de cartas Juegos de mesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('796','Atletismo y deportes');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('797','Deportes acuáticos Deportes aéreos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('798','Deportes hípicos Carreras');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('799','Deportes de caza, de pesca, de tiro al blanco');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('800','LITERATURA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('804','ENSAYOS CONFERENCIAS DISCURSOS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('808','COMPOSICIÓN LITERARIA RETÓRICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('808.8','COLECCIONES DE OBRAS DIVERSAS LITERATURAS ESCRITAS ORIGINALMENTE EN DIFERENTE IDIOMAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('809','HISTORIA DE LA LITERATURA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('810','LITERATURA NORTEAMERICANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('819','LITERATURA CANADIENSE');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('820','LITERATURA INGLESA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('830','LITERATURA ALEMANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('839','OTRAS LITERATURAS GERMÁNICAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('840','LITERATURA FRANCESA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('849','LITERATURA PROVENZAL');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('849.9','LITERATURA CATALANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('850','LITERATURA ITALIANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('859','LITERATURA RUMANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('859.9','LITERATURA RETORROMANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('860','LITERATURA CASTELLANA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('861','Poesía Épica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('862','Teatro');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('863','Novela - Fábulas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('864','Ensayos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('865','Oratoria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('866','Epístolas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('867','Sátira y humorismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('869','LITERATURA PORTUGUESA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('870','LITERATURA LATINA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('871','Poesía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('873','Poesía épica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('875','Oratoria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('876','Género epistolar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('877','Sátira y humorismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('878','Miscelánea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('879','OTRAS LITERATURAS ITÁLICAS, LATINA MEDIOEVAL Y MODERNA (LATÍN ECLESIÁSTICO)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('880','LITERATURA GRIEGA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('881','Poesía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('882','Poesía dramática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('883','Poesía épica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('884','Poesía lírica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('885','Oratoria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('886','Género epistolar');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('887','Sátira y humorismo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('888','Miscelánea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('889','GRUPO HELÉNICO, LITERATURA GRIEGA MODERNA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('890','LITERATURA DE OTRAS LENGUAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('891','Literaturas indoeuropeas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('892','Literaturas  semíticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('893','Literatura camítica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('894','Literaturas  tungusa, mogola, turco tártara, samoyeda, ugro-finesa y literaturas hiperbóreas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('894.7','Literatura caucásica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('894.8','Literatura dravítica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('895','Literaturas  chino-tibetana, japonesa-coreana, austroasiática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('896','Literaturas africanas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('897','Literaturas indígenas de América del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('898','Literaturas indígenas de América del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('899','Literaturas austronesias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('899.9','Otras literaturas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('900','HISTORIA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('909','HISTORIA MODERNA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('910','GEOGRAFÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('911','Geografía política e histórica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('912','Atlases');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('913','Geografía del mundo antiguo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('914','Geografía de Europa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('915','Geografía de Asia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('916','Geografía de Africa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('917','Geografía de América del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('918','Geografía de América del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('919','Geografía de Oceanía y regiones polares');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('920','BIOGRAFÍAS');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('929','Genealogía y heráldica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('930','HISTORIA ANTIGUA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('932','Egipto antiguo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('933','Civilización hebrea antigua');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('935','Historia del cercano oriente');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('936','Tribus europeas antiguas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('937','Roma antigua');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('938','Grecia antigua');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('939','Otras civilizaciones antiguas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('940','HISTORIA EUROPEA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('941','Escocia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('941.5','República Libre de Irlanda (EIRE)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('941.6','Irlanda del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('942','Inglaterraa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('942.9','Gales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943','Alemania');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.6','Austria');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.648','Lichtenstein');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.68','Trieste');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.7','Checoeslovaquia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.8','Polonia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('943.9','Hungría');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('944','Francia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('944.949','Mónaco');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('945','Italia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('945.4','San Marino');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('945.8','Malta');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946','España');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946.7','Andorra');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946.8','Gibraltar Islas Canarias');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946.9','Portugal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946.98','Madeira');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('946.99','Azores');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947','Unión de Repúblicas Socialistas Soviéticas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.1','Finlandia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.2','República Socialista Soviéntica Carelofilandesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.3','República Socialista Ruso-Soviéntica Federal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.4','República Socialista Soviéntica de Letonia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.41','República Socialista Soviéntica de Estonia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.5','República Socialista Soviéntica de Lituania');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.6','República Socialista Soviéntica de la Rusia blanca');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.7','República Socialista Soviéntica de Ucrania');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.9','República Socialista Soviéntica de Georgia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.91','República Socialista Soviéntica de Adserbeiyán');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('947.92','República Socialista Soviéntica de Armenia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('948','Escandinavia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('949','Otros países europeos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('950','HISTORIA DE ASIA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('951','China');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('952','Japón');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('953','Arabia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('954','India');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('954.1','Bután');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('954.2','Nepal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('954.7','Pakistán');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('954.8','Ceilán');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('955','Irán');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('956','Cercano Oriente');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('957','Rusia Soviética en Asia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('958','Asia Central del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('959','Indochina Francesa');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('959.1','Unión de Birmania');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('959.3','Tailandia (Siam)');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('959.5','Federación malaya');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('959.52','Singapur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('960','HISTORIA DE AFRICA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('961','Africa del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('962','   Egipto');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('963','   Etiopía');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('963.5','   Africa Oriental Italiana');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('964','   Marruecos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('965','   Argelia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('966','Africa Central del Norte');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('967','Africa Central del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('968','Africa del Sur');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('969','Islas del Océano Indico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('970','HISTORIA DE AMERICA DEL NORTE');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('971','Canadá');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('972','México');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('972.8','América Central');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('972.9','Islas Occidentales Antillas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('973','Estados Unidosa de Norteamérica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('974','Estados del Nordeste');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('975','Estados del Sudeste');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('976','Estados Centrales del Sur o del Golfo');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('977','Estados Centrales del Norte o de los Lagos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('978','Estados del Oeste o Montañosos');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('979','Estados del Pacífico');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('980','HISTORIA DE AMÉRICA DEL SUR');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('981','Brasil');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('982','Argentina');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('983','Chile');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('984','Bolivia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('985','Perú');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('986.1','Colombia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('986.2','Panamá');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('986.3','Canal de Panamá y Zona del Canal');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('986.6','Ecuador');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('987','Venezuela');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('988','Guayanas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('989.2','Paraguay');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('989.5','Uruguay');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('990','HISTORIA DE OCEANÍA');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('991','Indonesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('992','Islas de la Sonda');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('993','Nueva Zelandia Melanesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('994','Australia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('995','Papua Nueva Guinea');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('996','Polinesia Micronesia');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('997','Islas Pelágicas');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('998','Región Ártica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('999','Región Antártica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('518','Funciones especiales - Ecuaciones Diferenciales');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('536','Calor - Termodinámica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('539','Física molecular, nuclear, atómica - Mecánica Cuántica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('537','Electricidad y magnetismo. Teoría Electrodinámica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('511','Aritmética - Teoría de Conjuntos - Cálculo Proposicional');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('872','Poesía dramática');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('874','Poesía lírica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('391','Vestimenta y accesorios Cuidado del aspecto personal,');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('531','Mecánica de los sólidos - Mecánica Newtoniana - Mecánica Clásica');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('868','Miscelánea - Conversaciones');
INSERT INTO tblClasificacionDewey (id, nombre) VALUES ('152','Sensación Percepción Psicología de Masas');
