INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("A","Argentina");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("B","Bolivia");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("C","Colombia");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("CR","Costa Rica");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("Cu","Cuba");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("Ch","Chile");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("E","Ecuador");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("ES","El Salvador");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("G","Guatemala");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("Ho","Honduras");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("M","México");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("N","Nicaragua");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("P","Panamá");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("Pa","Paraguay");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("Pe","Perú");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("PR","Puerto Rico");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("U","Uruguay");
INSERT INTO `clasificacionLitHispanoamericana_860` (`Id`, `pais`) VALUES ("V","Venezuela");
