INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("000","OBRAS GENERALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("001","CONOCIMIENTO CIENCIA ERUDICIÓN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("002","EL LIBRO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("010","CIENCIA Y TÉCNICA BIBLIOGRÁFICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("011","Bibliografías generales y universales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("012","Bibliografías individuales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("013","Bibliografías de determinados grupos de autores");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("014","Bibliografías de obras anónimas y publicadas bajo seudónimo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("015","Bibliografías nacionales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("016","Bibliografías por materias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("017","Catálogos sistemáticos impresos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("018","Catálogos impresos de autores");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("019","Catálogos diccionarios impresos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("020","BIBLIOTECOLOGIA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("021","Creación, finalidad y desarrollo de las bibliotecas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("022","Edificios de bibliotecas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("023","Dirección y personal de la biblioteca");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("024","Reglamentos para uso de la biblioteca");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("025","Administración");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("026","Bibliotecas especializadas - Colecciones especiales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("027","Bibliotecas generales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("028","La lectura y su orientación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("029","Métodos y materia para el trabajo intelectual");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("030","ENCICLOPEDIAS GENERALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("031","Enciclopedias norteamericanas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("032","Enciclopedias británicas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("033","Enciclopedias alemanas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("034","Enciclopedias francesas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("035","Enciclopedias italianas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("036","Enciclopedias españolas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("037","Enciclopedias rusas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("038","Enciclopedias escandinavas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("039","Otras enciclopedias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("040","COLECCIONES DE ENSAYOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("050","PUBLICACIONES PERIODOCAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("060","SOCIEDADES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("069","MUSEOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("070","PERIODISMO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("071","Periódicos norteamericanos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("072","Periódicos ingleses");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("073","Periódicos alemanes");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("074","Periódicos franceses");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("075","Periódicos italianos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("076","Periódicos españoles");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("077","Periódicos rusos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("078","Periódicos escandinavos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("079","Historia individual de periódicos de otros países");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("080","POLIGRAFÍAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("081","Colecciones de obras de un solo autor");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("082","Colecciones de obras de varios autores");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("090","LIBROS RAROS Y CURIOSOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("091","Manuscritos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("092","Libros xilográficos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("093","Incunables");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("094","Impresiones raras y valiosas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("095","Encuadernaciones raras y valiosas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("096","Ilustraciones o materiales raros y valiosos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("097","Marcas del impresor Ex libris");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("098","Obras raras por sus caracteres extrínsecos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("100","FILOSOFÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("101","Estética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("109","Historia de la filosofía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("110","METAFÍSICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("111","Ontología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("112","Metodología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("113","Cosmología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("114","   Espacio");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("115","   Tiempo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("116","   Movimiento");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("117","   Materia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("118","   Energía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("119","   Cantidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("120","TEORÍAS METAFÍSICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("121","Gnoseología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("123","Libertad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("124","Teleología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("125","Infinito");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("128","El alma");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("130","RAMAS DE LA PSICOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("131","Psicología Fisiológica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("132","Psicología de anormales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("133","Ocultismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("134","Hipnotismo Mesmerismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("135","Sueños");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("136","Psicología  genética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("137","Psicología individual");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("138","Fisiognómica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("139","Frenología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("140","SISTEMAS FILOSÓFICOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("141","Idealismo Trascendentalismo Espiritualismo Subjetivismo Individualismo Romanticismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("142","Filosofía crítica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("143","Intuicionismo Bengsonismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("144","Empirismo Pragmatismo Humanismo Instrumentalismo Utilitarismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("145","Sensualismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("146","Naturalismo Materialismo Positivismo Atomismo Mecanicismo Neomecanicismo Dinamismo Energetismo Evolucionismo Transformismo Comtismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("147","Pamteísmo Panenteísmo Monismo Animismo Vitalismo Dualismo Pluralismo Paralelismo Ocasionalismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("148","Eclecticismo Liberalismo Sincretismo Dogmatismo Tradicionalismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("149","Otros sistemas filosóficos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("150","PSICOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("151","Inteligencia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("153","Cognición");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("154","Memoria Aprendizaje");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("155","Imaginación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("156","Intuición");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("157","Emoción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("158","Conación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("159","Motivación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("160","LÓGICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("161","Inducción y método científico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("162","Deducción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("163","Fe");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("164","Sistemas de lógica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("170","ÉTICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("171","Ética teórica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("172","Ética política");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("173","Moral de la familia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("174","Ética  profesional o moral en los negocios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("175","Moral en las diversiones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("176","Moral sexual");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("177","Ética  social");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("178","Ética  de la templanza");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("179","Otros sistemas de ética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("180","FILOSOFÍA ANTIGUA Y ORIENTAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("181","Filosofía oriental");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("182","Filosofía  presocrática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("183","Los sofistas y la filosofía socrática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("184","Filosofía platónica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("185","Filosofía aristotélica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("186","Escepticismo y neoplatonismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("187","Epicureísmo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("188","Estoicismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("189","Filosofía medioeval");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("190","FILOSOFÍA MODERNA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("191","Filosofía estadounidense");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("192","Filosofía  inglesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("193","Filosofía alemana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("194","Filosofía francesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("195","Filosofía italiana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("196","Filosofía española y portuguesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("197","Filosofía rusa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("198","Filosofía  escandinava");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("199","Otras filosofías modernas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("200","RELIGIÓN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("210","RELIGIÓN NATURAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("211","Deísmo Ateísmo Teísmo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("212","Panteísmo Teosofía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("213","Creación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("214","Providencia fatalismo Teodicea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("215","Religión y ciencia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("216","El bien y el mal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("217","Oración y culto");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("218","Inmortalidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("219","Analogías Doctrina de las correspondencias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("220","BIBLIA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("221","Antiguo Testamento");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("222","   Libros históricos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("223","   Libros sapienciales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("224","   Libros proféticos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("225","Nuevo Testamento");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("226","   Evangelios Hechos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("227","   Epístolas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("228","   Apocalipsis de San Juan");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("229","Libros apócrifos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("230","TEOLOGÍA SISTEMÁTICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("231","Dios La Trinidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("232","Cristología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("233","El Hombre");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("234","Soteriología Salvación Sacramentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("235","Santos Ángeles Demonios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("236","Escatología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("237","Vida Futura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("238","Fundamentos de la creencia religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("239","Apologética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("240","TEOLOGÍA PRÁCTICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("241","Teología moral");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("242","Meditación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("244","Cuentos Alegorías Sátiras");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("245","Himnología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("246","Simbolismos cristiano");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("247","Estética de la iglesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("248","Devición privada Ascética Mística");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("249","Devociones y oraciones en familia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("250","TEOLOGÍA PASTORAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("251","Homilética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("252","Sermones e instrucciones pastorales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("253","Ministros eclesiásticos Párrocos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("254","Administración eclesiástica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("258","Obra social de la iglesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("259","Organización y dirección de grupos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("260","IGLESIA CRISTIANA EN GENERAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("261","Teología social cristiana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("262","Gobierno de la iglesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("263","Día del Señor");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("264","Culto público");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("265","Sacramentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("266","Misiones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("267","Asociaciones religiosas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("268","Educación religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("269","Obra de conversión evangélica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("270","HISTORIA DE LA IGLESIA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("271","Ordenes religiosas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("272","Persecuciones religiosas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("273","Herejías");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("274-279","Historia de la iglesia en los diferentes países");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("280","IGLESIAS Y SECTAS CRISTIANAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("281","Iglesias primitivas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("282","Iglesia Católica Apostólica Romana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("283","Iglesia Anglicana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("284","Protestantismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("285","Presbiterianismo, congregacionalismo y otros grupos reformados");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("286","Iglesias baptistas y otras sectas que practican el bautismo por inmerisón");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("287","Metodismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("288","Unitarismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("289","Otras sectas cristianas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("290","RELIGIONES NO CRISTIANAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("291","Mitología comparada");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("292","Religión y mitología griega y romana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("293","Religión y mitología teutónica y nórdica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("294","Budismo y Brahmanismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("295","Religiones asiáticas no semíticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("296","Judaísmo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("297","Islamismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("299","Religiones semíticas y otrs religiones no cristianas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("300","CIENCIAS SOCIALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("301","SOCIOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("309","HISTORIA DE LAS CIENCIAS SOCIALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("310","ESTADÍSTICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("311","Métodos estadísticos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("312","Demografía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("320","CIENCIAS POLÍTICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("321","Tipos de Estado");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("322","Jurisdicción del Estado");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("323","Relaciones del Estadp con individuos o grupos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("324","Sufragio Elecciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("325","Migración internacional y colonización");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("326","Esclavitud");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("327","Relaciones internacionales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("328","Legislación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("329","Partidos políticos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("330","ECONOMÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("331","Trabajo y problemas del trabajo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("332","Finanzas privadas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("333","Economía de tierras");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("334","Cooperación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("335","Sistemas colectivistas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("336","Hacienda Pública");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("337","Política arancelaria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("338","Producción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("339","Ingreso y riqueza");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D340","DERECHO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D341","Derecho internacional");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D342","Derecho constitucional");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D343","Derecho penal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D344","Derecho administrativo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D345","Derecho procesal penal y civil");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D346","Derecho civil");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D347","Derecho comercial");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D348","Derechos especiales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("D349","Historia del derecho. Derecho clasificado por los países");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("350","ADMINISTRACIÓN PÚBLICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("351","Problemas de la administración pública");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("352","Gobierno local");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("353","Gobierno federal y estatal de los EE.UU. de Norteamérica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("354","Administración de las ramas del poder ejecutivo de otros países");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("355","Ciencia y arte militar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("356","Servivios y fuerzas terrestres");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("357","Caballería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("358","Fuerzas y servicios aéreos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("359","Fuerzas navales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("360","BIENESTAR SOCIAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("361","Servicio social e instituciones sociales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("362","Servicios de bienestar social");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("364","Criminología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("365","Penalogía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("366","Asociaciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("367","Clubes sociales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("368","Seguros");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("369","Otras asociaciones e instituciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("370","EDUCACIÓN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("371","Enseñanza");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("372","Enseñanza primaria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("373","Enseñanza secundaria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("374","Educación de adultos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("375","Programas de estudios (Curriculum) Programa de materias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("376","Educación femenina");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("377","Enseñanza moral y religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("378","Enseñanza universitaria y superior");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("379","La enseñanza y el estado");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("380","COMERCIO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("381","Comercio interior");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("382","Comercio internacional");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("383","Comunicación postal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("384","Comunicaciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("385","Transporte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("386","Transporte por ríos, canales y lagos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("387","Transporte marítimo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("387.7","Transporte aéreo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("388","Transporte por carreteras");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("389","Pesas y medidad Metrología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("390","COSTUMBRES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("392","Costumbres del ciclo de vida individual");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("393","Costumbres funerarias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("394","Costumbres políticas y sociales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("395","Etiqueta");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("396","Posición de la mujer en la sociedad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("397","Gitanos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("398","Folklore");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("399","Costumbres de guerra");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("400","LINGÜISTICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("408","COLECCIONES LENGUAS ARTIFICIALES UNIVERSALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("410","LINGÜISTICA COMPARADA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("411","Escritura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("412","Etimilogía Semántica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("413","Lexicografía Diccionarios políglotas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("414","Fonética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("415","Gramática Morfología Sintaxis");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("416","Prosodia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("417","Inscripciones Paleografía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("418","Textos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("419","Lenguaje mímico, simbólico o ideográfico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("420","INGLÉS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("430","ALEMÁN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("439","LENGUAS GERMÁNICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("440","FRANCES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("449","PROVENZAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("450","ITALIANO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("459","RUMANO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("460","CASTELLANO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("461","   Escritura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("462","   Derivaciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("463","   Diccionarios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("464","   Sinónimos Homónimos Antónimos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("465","   Gramática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("466","   Prosodia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("467","   Provincialismos Jerga Dialectología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("468","   Textos para la enseñanza del castellano");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("469","PORTUGUES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("470","LATÍN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("479","OTRAS LENGUAS ITÁLICAS LATÍN MEDIOEVAL Y MODERNO (LATÍN ECLESIÁSTICO)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("480","GRIEGO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("489","GRUPO HELÉNICO GRIEGO MODERNO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("490","OTRAS LENGUAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("491","Lenguas indoeuropeas e indo-hitita");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("492","Lenguas semíticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("493","Lenguas camíticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("494","Lenguas tungusas, mogolas, turco-tártaras, samoyedas, ugrofinesas y del grupo hiperbóreo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("495","Lenguas chino-tibetanas, japonesa-coreana, austroasiáticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("496","Lenguas africanas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("497","Lenguas de América del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("498","Lenguas de América del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("499","Lenguas austronesias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("500","CIENCIAS PURAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("508","COLECCIONES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("510","MATEMÁTICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("512","Álgebra");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("513","Geometría");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("514","Trigonometría");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("515","Geometría descriptiva");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("516","Geometría analítica euclideana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("517","Cálculo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("519","Probabilidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("520","ASTRONOMÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("521","Dinámica celeste");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("522","Observatorio e instrumentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("523","Astronomía descriptiva Astrofísica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("524","Mapas y tablas astronómicas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("525","Tierra");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("526","Geodesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("527","Astronomía aplicada a la navegación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("528","Almanaques naúticos y efemérides");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("529","Mediciones del tiempo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("530","FÍSICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("532","Mecánica de los líquidos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("533","Mecánica de los gases");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("534","Sonido");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("535","Óptica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("540","QUÍMICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("541","Fisicoquímica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("542","Aparatos y equipos para laboratorios químicos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("543","Análisis");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("544","Análisis cualitativo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("545","Análisis cuantitativo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("546","Química inorgánica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("547","Química Orgánica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("548","CRISTALOGRAFÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("549","MINERALOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("550","GEOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("551","Geología-física y dinámica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("552","Petrología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("553","Geología económica y aplicada");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("554","Geología de Europa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("555","Geología de Asia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("556","Geología de Africa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("557","Geología de América del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("558","Geología de América del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("559","Geología de Oceanía y de las regiones polares");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("560","PALEONTOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("561","Paleofitología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("562","Paleozoología de los invertebrados");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("563","Protozoa, porífera, cnidaria, achinodermata");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("564","Mollusca y Molluscoidea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("565","Arthropoda");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("566","Paleozoología de los vertebrados");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("567","Peces");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("568","Saurpsida (Reptiles y aves)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("569","Mammalia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("570","CIENCIAS BIOLÓGICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("571","Arquelogía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("572","Antropología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("573","Antropología física");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("574","Biología Ecología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("575","Evolución Genética");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("576","Microbiología");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("578","Técnicas biológicas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("579","Colecciones de historia natural y biológica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("580","BOTÁNICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("581","Fisiología y morfología vegetal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("582","Botánica sistemática o taxonómica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("583","Dicotiledóneas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("584","Monocotiledóneas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("585","Gimnospermas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("586","Criptógamas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("587","Pteridofitas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("588","Briofitas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("589","Talofitas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("590","ZOOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("591","Zoología general");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("592","Invertebrada");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("593","   Protozoa Mesozoa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("594","   Mollusca y molluscoidea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595","   Articulata");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.1","   Vermes");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.3","   Crustacea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.4","   Arachnida");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.5","   Onychophora");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.6","   Myriapoda");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("595.7","   Insecta (hexapoda)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("596","Chordates");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("597","   Peces");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("597.6","   Amphibia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("598","   Reptilia Aves");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("599","   Mammalia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("599.9","   Hombre");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("600","CIENCIA APLICADA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("608","PATENTE E INVENTOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("610","CIENCIAS MÉDICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("611","Anatomía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("612","Fisiología humana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("613","Higiene personal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("614","Salud pública y medicina preventiva");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("615","Terapéutica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("616","Patología interna y clínica médica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("617","Cirugía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("618","Ginecología y obstetricia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("618.9","Pediatría");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("618.97","GERONTOLOGÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("620","INGENIERÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("621","Ingeniería mecánica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("622","Ingeniería de minas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("623","Ingeniería militar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("624","Ingeniería estructural");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("625","Ingeniería del transporte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("627","Ingeniería hidráulica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("628","Ingeniería sanitaria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("629","Otras ramas de la ingeniería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("629.4","Viajes espaciales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("630","AGRICULTURA Y GANADERÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("631","Administración agrícola");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("632","Factores perjudiciales en la producción agrícola");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("633","Cultivos extensivos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("634","Fruticultura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("634.9","Dasonomía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("635","Horticultura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("636","Zootecnia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("637","Industria láctea y sus derivados");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("638","Cría de abejas, gusanos de seda y otros insectos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("639","Industria de la caza y de la pesca");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("640","ECONOMÍA DOMÉSTICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("641","Alimentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("642","Comidas y agasajos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("643","Plan de distribución de la casa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("645","Amueblado de la casa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("646","Indumentaria y aspecto personal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("647","Organización y administración de la casa y otros tipos de vivienda");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("648","Higiene y sanidad del hogar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("649","Cuidado de niños y enfermería en el hogar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("650","EMPRESAS Y SISYEMAS COMERCIALES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("651","Dirección de oficinas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("652","Escritura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("653","Taquigrafía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("655","Industria de las artes gráficas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("657","Contabilidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("658","Administración de empresas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("659","Otros temas relacionados con las empresas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("660","TECNOLOGÍA QUÍMICA QUÍMICA INDUSTRIAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("661","Productos químicos industriales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("662","Explosivos Tecnología de los combustibles Carbones de uso industrial");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("663","Bebidas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("664","Industria de los alimentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("665","Lubricantes Tecnología del petróleo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("666","Tecnología de la cerámica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("667","Limpieza y blanqueo Teñido");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("668","Otros materiales y productos de química orgánica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("669","Metalurgia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("670","MANUFACTURAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("671","Manufactura de metales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("672","Manufactura del hierro y del acero Aleaciones del hierro");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("673","Manufactura de otros metales y sus aleaciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("674","Industria de la madera");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("675","Industria de cueros y pieles");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("676","Manufactura de pulpa, papel y celulosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("677","Industria de textiles y de otros fibras");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("678","Caucho y manufacturas de caucho");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("679","Otras manufacturas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("680","MANUFACTURAS (Continuación)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("681","Manufacturas de instrumentos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("682","Herrería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("683","Armería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("684","Carpintería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("685","Manufactura de artículos de cuero");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("687","Industria de la ropa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("688","Fabricación de artículos pequeños");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("690","CONSTRUCCIÓN DE EDIFICIOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("691","Materiales de construcción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("692","Prácticas de construcción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("693","Sistemas de Construcción");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("694","Construcción en madera");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("695","Detalles de construcción de edificios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("696","Accesorios para construcción de edificios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("697","Técnicas de calefacción, ventilación y acondicionamiento de aire");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("698","Decoración de edificios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("700","ARTES Y RECREACIÓN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("701","FILOSOFÍA Y TEORÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("704","ENSAYOS, CONFERENCIAS, DISCURSOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("708","GALERÍAS, MUSEOS Y COLECCIONES PARTICULARES");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("709","HISTORIA DEL ARTE");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("710","ARQUITECTURA PAISAJISTA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("711","Planeamiento regional y urbano");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("712","Tipos de diseño de arquitectura paisajista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("713","Formación y conservación del paisaje");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("714","Temas acuáticos en arquitectura paisajista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("715","Árboles, arbustos y setos en arquitectura paisajista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("716","Plantas herbáceas o anuales en la arquitectura paisajista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("717","Construcción en arquitectura paisajista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("718","Planeamiento de cementerios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("719","Planeaminero de reservaciones de tierras y preservación del paisaje natural");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("720","ARQUITECTURA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("721","Construcción arquitectónica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("722","Arquitectura antigua");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("723","Arquitectura medioeval");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("724","Arquitectura moderna");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("725","Edificios públicos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("726","Arquitectura religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("727","Edificios de enseñanza");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("728","Arquitectura residencial");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("729","Diseños arquitectónicos y decoración");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("730","ESCULTURA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("731","Métodos y material");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("732","Escultura antigua Escultura primitiva");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("733","Escultura clásica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("734","Escultura medioeval");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("735","Escultura moderna");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("736","Talla de materiales especiales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("737","Numismática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("738","Escultura en cerámica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("739","Escultura en metal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("740","DIBUJO ARTE DECORATIVO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("741","Dibujo a pulso");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("742","Perspectiva");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("743","Anatomía en el dibujo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("744","Dibujo técnico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("745","Arte decorativo y diseño");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("746","Encajes Tapices tranajos de aguja");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("747","Decoración de interiores");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("748","Cristalería");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("749","Muebles y accesorios");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("750","PINTURA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("751","Métodos y material");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("752","Teoría y aplicación del color");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("753","Pintura épica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("754","Pintura costumbrista");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("755","Pintura religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("756","Pintura histórica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("757","Retratos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("758","Otros temas en pintura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("759","Historia de la pintura");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("760","GRABADO Y TÉCNICAS DE GRABADO");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("761","Grabado en relieve");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("762","Grabado en hueco (Intaglio) Granago en metal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("763","Grabado en superficie plana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("764","Cromolitografía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("765","Grabado en línea Grabado a puntos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("766","Aguatinta Mezzotinta");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("767","Aguafuerte Grabado a punta seca");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("768","Grabado mecánico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("769","Colecciones de grabados");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("770","FOTOGRAFÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("771","Material fotográfico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("772","Procedimientos fotográficos con sales metálicas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("773","Procedimientos fotográficos de pigmentación");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("778","Aplicaciones de la fotografía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("779","Colecciones de fotografías");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("780","MÚSICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("781","Teoría y técnica de la música");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("782","Música operística Música para la escena");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("783","Música religiosa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("784","Música vocal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("785","Conjuntos instrumentales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("786","Instrumentales de teclado");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("787","Instrumentos de cuerda");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("788","Instrumentos de viento");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("789","Instrumentos de percusión Instrumentos mecánicos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("790","RECREACIÓN");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("791","Diversiones y espectáculos públicos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("792","Teatro");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("793","Tertulias Otros entrenimientos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("794","Juegos de habilidad");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("795","Juegos de cartas Juegos de mesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("796","Atletismo y deportes");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("797","Deportes acuáticos Deportes aéreos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("798","Deportes hípicos Carreras");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("799","Deportes de caza, de pesca, de tiro al blanco");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("800","LITERATURA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("804","ENSAYOS CONFERENCIAS DISCURSOS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("808","COMPOSICIÓN LITERARIA RETÓRICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("808.8","COLECCIONES DE OBRAS DIVERSAS LITERATURAS ESCRITAS ORIGINALMENTE EN DIFERENTE IDIOMAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("809","HISTORIA DE LA LITERATURA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("810","LITERATURA NORTEAMERICANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("819","LITERATURA CANADIENSE");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("820","LITERATURA INGLESA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("830","LITERATURA ALEMANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("839","OTRAS LITERATURAS GERMÁNICAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("840","LITERATURA FRANCESA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("849","LITERATURA PROVENZAL");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("849.9","LITERATURA CATALANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("850","LITERATURA ITALIANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("859","LITERATURA RUMANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("859.9","LITERATURA RETORROMANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("860","LITERATURA CASTELLANA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("861","Poesía Épica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("862","Teatro");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("863","Novela - Fábulas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("864","Ensayos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("865","Oratoria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("866","Epístolas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("867","Sátira y humorismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("869","LITERATURA PORTUGUESA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("870","LITERATURA LATINA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("871","Poesía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("873","Poesía épica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("875","Oratoria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("876","Género epistolar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("877","Sátira y humorismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("878","Miscelánea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("879","OTRAS LITERATURAS ITÁLICAS, LATINA MEDIOEVAL Y MODERNA (LATÍN ECLESIÁSTICO)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("880","LITERATURA GRIEGA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("881","Poesía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("882","Poesía dramática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("883","Poesía épica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("884","Poesía lírica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("885","Oratoria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("886","Género epistolar");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("887","Sátira y humorismo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("888","Miscelánea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("889","GRUPO HELÉNICO, LITERATURA GRIEGA MODERNA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("890","LITERATURA DE OTRAS LENGUAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("891","Literaturas indoeuropeas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("892","Literaturas  semíticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("893","Literatura camítica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("894","Literaturas  tungusa, mogola, turco tártara, samoyeda, ugro-finesa y literaturas hiperbóreas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("894.7","Literatura caucásica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("894.8","Literatura dravítica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("895","Literaturas  chino-tibetana, japonesa-coreana, austroasiática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("896","Literaturas africanas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("897","Literaturas indígenas de América del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("898","Literaturas indígenas de América del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("899","Literaturas austronesias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("899.9","Otras literaturas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("900","HISTORIA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("909","HISTORIA MODERNA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("910","GEOGRAFÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("911","Geografía política e histórica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("912","Atlases");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("913","Geografía del mundo antiguo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("914","Geografía de Europa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("915","Geografía de Asia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("916","Geografía de Africa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("917","Geografía de América del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("918","Geografía de América del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("919","Geografía de Oceanía y regiones polares");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("920","BIOGRAFÍAS");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("929","Genealogía y heráldica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("930","HISTORIA ANTIGUA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("932","Egipto antiguo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("933","Civilización hebrea antigua");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("935","Historia del cercano oriente");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("936","Tribus europeas antiguas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("937","Roma antigua");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("938","Grecia antigua");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("939","Otras civilizaciones antiguas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("940","HISTORIA EUROPEA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("941","Escocia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("941.5","República Libre de Irlanda (EIRE)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("941.6","Irlanda del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("942","Inglaterraa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("942.9","Gales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943","Alemania");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.6","Austria");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.648","Lichtenstein");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.68","Trieste");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.7","Checoeslovaquia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.8","Polonia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("943.9","Hungría");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("944","Francia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("944.949","Mónaco");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("945","Italia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("945.4","San Marino");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("945.8","Malta");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946","España");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946.7","Andorra");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946.8","Gibraltar Islas Canarias");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946.9","Portugal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946.98","Madeira");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("946.99","Azores");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947","Unión de Repúblicas Socialistas Soviéticas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.1","Finlandia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.2","República Socialista Soviéntica Carelofilandesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.3","República Socialista Ruso-Soviéntica Federal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.4","República Socialista Soviéntica de Letonia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.41","República Socialista Soviéntica de Estonia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.5","República Socialista Soviéntica de Lituania");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.6","República Socialista Soviéntica de la Rusia blanca");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.7","República Socialista Soviéntica de Ucrania");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.9","República Socialista Soviéntica de Georgia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.91","República Socialista Soviéntica de Adserbeiyán");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("947.92","República Socialista Soviéntica de Armenia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("948","Escandinavia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("949","Otros países europeos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("950","HISTORIA DE ASIA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("951","China");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("952","Japón");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("953","Arabia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("954","India");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("954.1","Bután");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("954.2","Nepal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("954.7","Pakistán");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("954.8","Ceilán");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("955","Irán");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("956","Cercano Oriente");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("957","Rusia Soviética en Asia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("958","Asia Central del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("959","Indochina Francesa");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("959.1","Unión de Birmania");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("959.3","Tailandia (Siam)");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("959.5","Federación malaya");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("959.52","Singapur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("960","HISTORIA DE AFRICA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("961","Africa del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("962","   Egipto");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("963","   Etiopía");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("963.5","   Africa Oriental Italiana");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("964","   Marruecos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("965","   Argelia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("966","Africa Central del Norte");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("967","Africa Central del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("968","Africa del Sur");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("969","Islas del Océano Indico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("970","HISTORIA DE AMERICA DEL NORTE");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("971","Canadá");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("972","México");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("972.8","América Central");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("972.9","Islas Occidentales Antillas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("973","Estados Unidosa de Norteamérica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("974","Estados del Nordeste");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("975","Estados del Sudeste");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("976","Estados Centrales del Sur o del Golfo");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("977","Estados Centrales del Norte o de los Lagos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("978","Estados del Oeste o Montañosos");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("979","Estados del Pacífico");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("980","HISTORIA DE AMÉRICA DEL SUR");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("981","Brasil");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("982","Argentina");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("983","Chile");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("984","Bolivia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("985","Perú");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("986.1","Colombia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("986.2","Panamá");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("986.3","Canal de Panamá y Zona del Canal");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("986.6","Ecuador");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("987","Venezuela");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("988","Guayanas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("989.2","Paraguay");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("989.5","Uruguay");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("990","HISTORIA DE OCEANÍA");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("991","Indonesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("992","Islas de la Sonda");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("993","Nueva Zelandia Melanesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("994","Australia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("995","Papua Nueva Guinea");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("996","Polinesia Micronesia");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("997","Islas Pelágicas");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("998","Región Ártica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("999","Región Antártica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("518","Funciones especiales - Ecuaciones Diferenciales");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("536","Calor - Termodinámica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("539","Física molecular, nuclear, atómica - Mecánica Cuántica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("537","Electricidad y magnetismo. Teoría Electrodinámica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("511","Aritmética - Teoría de Conjuntos - Cálculo Proposicional");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("872","Poesía dramática");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("874","Poesía lírica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("391","Vestimenta y accesorios Cuidado del aspecto personal,");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("531","Mecánica de los sólidos - Mecánica Newtoniana - Mecánica Clásica");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("868","Miscelánea - Conversaciones");
INSERT INTO `clasificacionDewey` (`id`, `Nombre`) VALUES ("152","Sensación Percepción Psicología de Masas");
